клиент: {
	shape: image
	icon: ./pc.jpg 
}

web-сервер: {
	shape: image
	icon: ./web-server.jpg 
}

сервер приложений: {
	shape: image
	icon: ./app-server.jpg 
}

cms.файловая система: {
	shape: cylinder
}

cms.база данных: {
	shape: cylinder
}


клиент <-> web-сервер <-> сервер приложений <-> cms.управление контентом <-> cms.база данных

cms.управление контентом -> cms.файловая система
