дизайнеры: {
  shape:person
}
администраторы: {
  shape:person
}
группа внедрения: {
  shape:person
}
авторы контента: {
  shape:person
}

дизайнеры			-> cms: Шаблоны оформления
администраторы		-> cms: Управление пользователями
группа внедрения	-> cms: Настройка CMS
авторы контента	-> cms: Контент

cms <-> Сервер БД: Контент	
cms -> Сервер БД: Генерация схемы данных	

