direction: right

server: {
shape: image
icon: https://icons.terrastruct.com/tech/022-server.svg
}

client: {
shape: image
icon: ./client.svg

}

client -> server: HTTP GET {
  style: {
    font-size: 21
	 font-color: black
  }
}

