#+TITLE: Трудовые ресурсы
#+AUTHOR: Кормышев Егор ИСиП-301
#+DATE: \today
#+LANGUAGE: ru
#+LaTeX_HEADER: \usepackage[russian]{babel}


* Персонал организации, признаки и классификация, структура

Трудовые ресурсы (персонал, кадры) -  работники предприятия, выполняющие
управленческие, организационные и производственные функции. Уровень квалификации
работников определяется трудовой принадлежностью и выбранной профессии. Выбор
профессии зависит от приобретенной специальности, т.е. той суммы знаний конкретной
области деятельности, которую работник приобрел в учебном заведении.

** Структура трудовых ресурсов

Состав и количественные соотношения отдельных категорий и групп работников
предприятия характеризует структуру кадров.

Кадры предприятия (персонал, трудовые ресурсы) непосредственно связанные с
процессом производства продукции, т.е. занятые основной производственной
деятельностью, представляют промышленно – производственный персонал (ППП).

Работники торговли и общественного питания жилищного хозяйства, медицинских и
оздоровительных учреждений, учебных заведений и курсов, а также учреждений
дошкольного воспитания и культуры, состоящих на балансе предприятия относятся к
непромышленному персоналу предприятия (НПП).

Работники ППП подразделяются на две основные группы – рабочие и служащие. При
этом в группе служащих выделяются такие категории работающих, как руководители,
специалисты и собственно служащие. Рабочие обычно подразделяются на основных и
вспомогательных.
К
/руководителям/
относятся лица, наделенные полномочиями принимать
управленческие решения и организовывать их выполнение. Они подразделяются на
линейных, возглавляющих относительно обособленные хозяйственные системы, и
функциональных, возглавляющих функциональные отделы или службы (главный
бухгалтер, главный инженер, лавный механик, главный технолог, главный экономист и
др.).
К
специалистам
относиться относятся работники, занятые инженерно –
техническими,
экономическими,
бухгалтерскими,
юридическими
аналогичными видами деятельности.
К собственно служащим относятся работники, осуществляющие подготовку и
оформление документации, учет и контроль, хозяйственное обслуживание и дело
производство (агенты, кассиры, контролеры, чертежники и др.)
Соотношение перечисленных категорий работников в общей их численности,
выраженное в процентах, называется структурой кадров.

***** Управление кадрами

Представляет собой часть менеджмента, связанную с трудовыми ресурсами
предприятия. Его основными задачами являются удовлетворение потребности
предприятия в кадрах; обеспечение расстановки, профессионально – квалификационного
и должностного продвижения кадров; эффективное использование трудового потенциала
предприятия.
Обеспечение потребности в кадрах действующего предприятия предполагает не
только определение численности работников, но и текучести кадров, определение
дополнительной потребности или избытка кадров.
Под текучестью кадров понимается выраженная в процентах отношения числа
уволенных по собственному желанию, за прогулы и другие нарушения трудовой
дисциплины работников за определенный период времени к среднесписочной их
численности за тот же период времени. Она определяется по формуле:

# Ктек.=(Руф/Рсп)*100%

#+begin_export latex
\begin{equation}
k_{\text{тек}} = (P_{\text{уф}}/P_{\text{сп}})*100\%  
\end{equation}
#+end_export
