#+TITLE: Трудовые ресурсы
#+AUTHOR: Кормышев Егор ИСиП-301
#+DATE: \today
#+LANGUAGE: ru
#+LaTeX_HEADER: \usepackage[russian]{babel}


* Персонал организации, признаки и классификация, структура

Трудовые ресурсы (персонал, кадры) -  работники предприятия, выполняющие
управленческие, организационные и производственные функции. Уровень квалификации
работников определяется трудовой принадлежностью и выбранной профессии. Выбор
профессии зависит от приобретенной специальности, т.е. той суммы знаний конкретной
области деятельности, которую работник приобрел в учебном заведении.

** Структура трудовых ресурсов

Состав и количественные соотношения отдельных категорий и групп работников
предприятия характеризует структуру кадров.

Кадры предприятия (персонал, трудовые ресурсы) непосредственно связанные с
процессом производства продукции, т.е. занятые основной производственной
деятельностью, представляют промышленно – производственный персонал (ППП).

Работники торговли и общественного питания жилищного хозяйства, медицинских и
оздоровительных учреждений, учебных заведений и курсов, а также учреждений
дошкольного воспитания и культуры, состоящих на балансе предприятия относятся к
непромышленному персоналу предприятия (НПП).

Работники ППП подразделяются на две основные группы – рабочие и служащие. При
этом в группе служащих выделяются такие категории работающих, как руководители,
специалисты и собственно служащие. Рабочие обычно подразделяются на основных и
вспомогательных.
К
/руководителям/
относятся лица, наделенные полномочиями принимать
управленческие решения и организовывать их выполнение. Они подразделяются на
линейных, возглавляющих относительно обособленные хозяйственные системы, и
функциональных, возглавляющих функциональные отделы или службы (главный
бухгалтер, главный инженер, лавный механик, главный технолог, главный экономист и
др.).
К
специалистам
относиться относятся работники, занятые инженерно –
техническими,
экономическими,
бухгалтерскими,
юридическими
аналогичными видами деятельности.
К собственно служащим относятся работники, осуществляющие подготовку и
оформление документации, учет и контроль, хозяйственное обслуживание и дело
производство (агенты, кассиры, контролеры, чертежники и др.)
Соотношение перечисленных категорий работников в общей их численности,
выраженное в процентах, называется структурой кадров.

** Управление кадрами

Представляет собой часть менеджмента, связанную с трудовыми ресурсами
предприятия. Его основными задачами являются удовлетворение потребности
предприятия в кадрах; обеспечение расстановки, профессионально – квалификационного
и должностного продвижения кадров; эффективное использование трудового потенциала
предприятия.
Обеспечение потребности в кадрах действующего предприятия предполагает не
только определение численности работников, но и текучести кадров, определение
дополнительной потребности или избытка кадров.
Под текучестью кадров понимается выраженная в процентах отношения числа
уволенных по собственному желанию, за прогулы и другие нарушения трудовой
дисциплины работников за определенный период времени к среднесписочной их
численности за тот же период времени. Она определяется по формуле:

# Ктек.=(Руф/Рсп)*100%

#+begin_export latex
\begin{equation}
k_{\text{тек}} = (P_{\text{уф}}/P_{\text{сп}})*100\%  
\end{equation}
#+end_export



 


* Нормы труда

Для рассчета численности персонала каждой организации необходимы нормы труда

Нормы труда делятся на:

- Нормы времени (трудоемкость)
- Нормы выработки
- Нормы обслуживания
- Нормы управляемости
- Нормы численности


*** Норма времени (трудоемкость)

Обозначение: $H_{t}$ или Т_{штуч}

Устанавливается в *минутах* или *часах* на 1 операцию/изделие

Определяется по формуле:

#+begin_export latex
\begin{equation}
  H_{t} = t_{\text{пз}} + t_{\text{оп}} + t_{\text{об}} + t_{\text{огл}}
\end{equation}

\begin{equation}
  T_{\text{штуч}} = t_{\text{оп}} + t_{\text{об}} + t_{\text{огл}}
\end{equation}
#+end_export

Где:

- $t_{\text{пз}}$ - подготовительно-заключительное
- $t_{\text{оп}}$ - Оперативная работа (определяется по тех.рассчетам, данным хронометража или фоторграфии рабочего времени)
- $t_{\text{об}}$ - Время обслуживания рабочего места или оборудования (устанавливается по отрослевым нормативам в % от $t_{оп}$ (основной)) 
- $t_{\text{отл}}$ - Время на отдых и личные надобности

** Норма выработки

Показывает кол-во продукции в ед времени \\

Обозначение: $H_{\text{в}}$ \\

Устанавливается в кг/л/шт... \\

Определяется по формуле:

#+begin_export latex
\begin{equation}
  H_{\text{в}} = \frac{1}{H_{t}}
\end{equation}
#+end_export

** Норма обслуживания

Оборудование которое должен обслужить 1 человек \\

Обозначение: $H_{\text{обс}}$

** Норма управляемости

Оптимальное кол-во персонала, которым может эффективно управлять руководитель

Обозначение: $H_{\text{у}}$

** Норма численности

Устанавливается для некоторых категорий работников, если нет возможности рассчитать нормы труда по выше перечисленным способам \\

Обозначение: $H_{\text{ч}}$
