Нужды и потребности пользователей --> Проектные решения
Нужды и потребности пользователей --> Исходный код
Нужды и потребности пользователей --> Программа
Нужды и потребности пользователей --> Стандартные правила
